Tests for models
ChristianChidiac/harmonIQ pull request #64
Opened 2024-07-17 03:44 UTC by ChristianChidiac

2024-07-23 05:56 UTC, sbaljeet13 requested changes

2024-07-23 05:56 UTC, sbaljeet13 commented on src/main/java/com/group6/harmoniq/models/Quiz.java
> +     public void setId(Long id) {
Adding a new methond or exposing a readonly field just for testing is usually not a good approach. The tests should be adapted to the model or unit of code that we are trying to test, not other way around. In this case, we can skip the getId test if its not possible without adding this method to the model

2024-07-23 05:56 UTC, sbaljeet13 commented on src/main/java/com/group6/harmoniq/models/RecognitionQuiz.java
> +    public void setId(Long id) {
This should also be removed

2024-07-23 05:56 UTC, sbaljeet13 commented on src/main/java/com/group6/harmoniq/models/User.java
> +    public void setUId(Long uid) {
And this as well

2024-07-23 05:56 UTC, sbaljeet13 commented on src/test/java/com/group6/harmoniq/models/ArtistTest.java
> +import org.springframework.util.Assert;
I think these are unused and can be removed
```suggestion

```

2024-07-23 05:56 UTC, sbaljeet13 commented on src/test/java/com/group6/harmoniq/models/QuizTest.java
> +import org.springframework.util.Assert;
These are also unused

2024-07-23 05:56 UTC, sbaljeet13 commented on src/test/java/com/group6/harmoniq/models/RecognitionQuizTest.java
> +import org.springframework.util.Assert;
These also seem unused

2024-07-23 05:56 UTC, sbaljeet13 commented on src/test/java/com/group6/harmoniq/models/TrackTest.java
> +import org.springframework.util.Assert;
Some of these are also unused

2024-07-23 05:56 UTC, sbaljeet13 commented on src/test/java/com/group6/harmoniq/models/UserTest.java
> +import static org.junit.jupiter.api.Assertions.fail;
```suggestion

```

2024-07-23 05:56 UTC, sbaljeet13 commented on src/test/java/com/group6/harmoniq/models/UserTest.java
> +import org.springframework.util.Assert;
```suggestion

```

2024-07-23 23:03 UTC, sbaljeet13 approved these changes

2024-07-24 11:32 UTC, LanceWWS approved these changes

2024-07-24 15:43 UTC, merged