Update collaborative playlist with new styles
ChristianChidiac/harmonIQ pull request #80
Opened 2024-07-26 23:17 UTC by michellepark53

Styles updated: collaborative playlist, pop-ups for adding songs and non-collaborator users

2024-07-27 22:30 UTC, sbaljeet13 approved these changes

2024-07-29 03:12 UTC, LanceWWS submitted a review, later dismissed

2024-07-29 03:15 UTC, sbaljeet13 commented
Wait for #79 to merge

2024-07-29 03:16 UTC, sbaljeet13 requested changes, later dismissed
#79 need to be merged before

2024-07-30 07:19 UTC, mononomori approved these changes

2024-07-30 07:29 UTC, ChristianChidiac approved these changes

2024-07-30 08:08 UTC, LanceWWS approved these changes

2024-07-30 16:12 UTC, merged